
name: Dispatch workflow in repo with submodule
on:
  push:
    paths:
      - probe-rs/targets/**

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: julianguide/probe.rs
          event-type: update
          # github.event should contain these values: https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
          client-payload: '{"event_name": "${{ github.event_name }}", "head_commit_message": "${{ github.event.head_commit.message }}"}'